# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-20 11:06
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tradezone', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='beginnersguide',
            name='text1',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='beginnersguide',
            name='text2',
            field=models.TextField(default=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='beginnersguide',
            name='text3',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='beginnersguide',
            name='text4',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='beginnersguide',
            name='text5',
            field=models.TextField(default='Text1'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='beginnersguide',
            name='text6',
            field=models.TextField(default='Text3'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='beginnersguide',
            name='text7',
            field=models.TextField(default='text8'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='beginnersguide',
            name='text8',
            field=models.TextField(default='text8'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='beginnersguide',
            name='publish',
            field=models.DateTimeField(default=datetime.datetime(2018, 11, 20, 11, 3, 46, 306360, tzinfo=utc)),
        ),
    ]
