# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-30 10:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Registrations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FirstName', models.CharField(max_length=30)),
                ('LastName', models.CharField(max_length=30)),
                ('PanNumber', models.CharField(max_length=30)),
                ('uname', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=40)),
            ],
        ),
    ]
