# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-29 14:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registerForm', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RegisterForm',
            new_name='Register',
        ),
    ]
