# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-31 16:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jobName', models.CharField(max_length=30)),
                ('jobType', models.CharField(max_length=30)),
                ('jobLoc', models.CharField(max_length=30)),
            ],
        ),
    ]
